/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.4.32"
    application
}
repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.31")
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("com.squareup:javapoet:1.10.0")
    implementation("com.squareup:kotlinpoet:1.8.0")
    implementation("io.insert-koin:koin-core-jvm:3.0.1-beta-2")
//    implementation("org.koin:koin-test-junit4:3.0.1-alpha-1")
//    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.4.31")
//    testImplementation("org.koin:koin-test:3.0.1-alpha-5")
}

group = "me.shaheen"
version = "1.0-SNAPSHOT"
description = "cdc-test-gen"
java.sourceCompatibility = JavaVersion.VERSION_1_8


tasks.test {
    useJUnitPlatform()
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>() {
    kotlinOptions.jvmTarget = "13"
}

application {
    mainClassName = "presentation.consoleKt"
}