/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1.1/userguide/multi_project_builds.html
 */
rootProject.name = "Contractor"
include(":core")
include(":provider")
include(":consumer")
project(":core").projectDir = File("./core")
project(":provider").projectDir = File("./provider")
project(":consumer").projectDir = File("./consumer")
include("evaluation")
